### ISSUE TITLE
Review list of proposed ScanCode exclusions for default configuration.

### ISSUE THREAD

**Issue by mrutkows** [apache/openwhisk-release#116]
Looking at issue (apigateway): https://github.com/apache/incubator-openwhisk-apigateway/issues/273

It includes what looks like a comprehnsive list of exclusions for all repos. (verify with @daisy-ycguo).  They appear a follows:

```
**/*.json
**/**.gradle
**/gradlew
**/gradle/**
**/.**
**/templates/**
**/*.j2.*
**/.github/**
**/auth.whisk.system
**/auth.guest
**/i18n_resources.go
```

we should review this list, discuss and open an Issue for update to ScanCode in the utilities repo. once we agree.

**Comment by mrutkows** [comment]
My first comment is that scancode default config today excludes "wski18n" which includes all JSON and generated file "i18n_resources.go"; do we wish the default config to be more precise by listing "i18n_resources.go" and use the default *.json to get all the country specific data files used for translated strings?

**Comment by mrutkows** [comment]
@daisy-ycguo @houshengbo we reviewed this list of exclusions and confirmed it was a summary or accumulation of all exclusions for all repos. that was created in March.  These should be reflected in scanCode.py.

**Comment by dgrove-oss** [comment]
Closing as outdated
