### ISSUE TITLE
"Test data files" that need ASF license not well described

### ISSUE THREAD

**Issue by mrutkows** [apache/openwhisk-release#129]
The [license_compliance.md](https://github.com/apache/incubator-openwhisk-release/blob/master/docs/license_compliance.md) file lists files (types) that should have an ASF license.  

In the "must include" table, " Test data files" are listed (for tests) as among those that should have license headers; however, there are no examples (e.g., one or more file types, or specific names of files that caused us to add this row to the table).

In addition, we say that "data files" like JSON can be excluded from having a license header (unsupported).  Since JSON files could also be used as input data (for tests), not just for configuration data, we should clarify what is meant by "Test data files" and be as specific as possible.

**Comment by houshengbo** [comment]
We do not release the test data files for the first release. We can revisit this issue in future if we decide to release the tests.

**Comment by dgrove-oss** [comment]
We've dealt with this.
