### ISSUE TITLE
 Step 5: Add NOTICE, LICENSE, and CHANGELOG to each OpenWhisk project

### ISSUE THREAD

**Issue by houshengbo** [apache/openwhisk-release#13]
This step can lead to multiple issues for each openwhisk repo to implement by adding NOTICE, LICENSE and CHANGELOG separately. 

The important thing we need to confirm is which files are static in content, and which are dynamic based on different releases.

This step can make sure in further steps that we can package the all the necessary files.

Sub-issues can be opened to track this epic.

**Comment by daisy-ycguo** [comment]
NOTICE files have been added to 12 repo:
https://github.com/apache/incubator-openwhisk/pull/3522
https://github.com/apache/incubator-openwhisk-cli/pull/265
https://github.com/apache/incubator-openwhisk-client-go/pull/74
https://github.com/apache/incubator-openwhisk-apigateway/pull/286
https://github.com/apache/incubator-openwhisk-catalog/pull/266
https://github.com/apache/incubator-openwhisk-runtime-docker/pull/25
https://github.com/apache/incubator-openwhisk-runtime-java/pull/29
https://github.com/apache/incubator-openwhisk-runtime-nodejs/pull/34
https://github.com/apache/incubator-openwhisk-runtime-php/pull/12
https://github.com/apache/incubator-openwhisk-runtime-python/pull/14
https://github.com/apache/incubator-openwhisk-runtime-swift/pull/43
https://github.com/apache/incubator-openwhisk-wskdeploy/pull/842

The updates include:
- Change the extension to `txt`
- Add declaration of dependencies which are NON Apache License
- Append NOTICE file of those dependencies which are Apache License.

**Comment by houshengbo** [comment]
The LICENSE and NOTICE files have been added to the 12 repos we are about to release for the first time in Apache. 

We will resolve the issue regarding CHANGELOG during next source code release.
