### ISSUE TITLE
Add ASF license to ISSUE_TEMPLATE.md under .github

### ISSUE THREAD

**Issue by mrutkows** [apache/openwhisk-release#158]
Many of our repos. are creating "issue templates" by creating a file called ISSUE_TEMPLATES.md under the directory ".github".   It would be conformant to our policy to add the ASF License headers to these markdown files so we do not need to list the ".github" directory as an exclusion in scancode.

Please note, this is not something that gets packaged and will not affect our source release plans, but it would be good to have conformance even for build/process/tooling files.

for example (as of this authoring) are currently affected among the repos. intended for source code release (and likely will affect many other of our extended family repos.):
```
./incubator-openwhisk-runtime-php/.github
./incubator-openwhisk-runtime-java/.github
./incubator-openwhisk/.github
./incubator-openwhisk-runtime-swift/.github
./incubator-openwhisk-runtime-nodejs/.github
./incubator-openwhisk-runtime-docker/.github
./incubator-openwhisk-runtime-python/.github
```

**Comment by houshengbo** [comment]
.github is excluded in the source code release.
