### ISSUE TITLE
Move scancode before Lua test dependencies are installed

### ISSUE THREAD

**Issue by mrutkows** [apache/openwhisk-release#168]
Currently scancode runs AFTER many Lua test dependencies are installed as part the ```install``` Travis step in "isntsall-deps.sh":

````
install:
  - cd tests
- ./install-deps.sh
```

but, scancode runs in the later Travis step ```script``` which forces our ASF-Release.cfg having to exclude directories ```lua_install``` and ```tests/lua_modules``` which we should not even be scanning. 

We should try and move the invocation of "scancode" to right after we install it in the "setup.sh" travis script.

**Comment by houshengbo** [comment]
Files, like .travis.yml, they are not in the artifacts to be released, so we do not need to worry about it.

**Comment by mrutkows** [comment]
This was not intended to be a gating issue for source release, but it is an issue that needs to be still addressed.

**Comment by mrutkows** [comment]
Tried to do this in PR https://github.com/apache/incubator-openwhisk-apigateway/pull/306 (closed), but the scan results do not appear (too early in logs) and it does not appear to stop "scripts" from running if an error occurs...  will need to revisit later.

**Comment by dgrove-oss** [comment]
This has been dealt with.
