### ISSUE TITLE
Verify each TAR has changes(.md or .txt) included 

### ISSUE THREAD

**Issue by mrutkows** [apache/openwhisk-release#178]
and perhaps make sure hat this file gets checked into main OW github as well..  

I know we have a utility/script Daisy produced, but not sure where it puts the changelog file, what it is called and confirm it is added to each repo's .tar file

FYI, The Apache Beam project is generating and including it from JIRA (open issues against Fix version)... https://beam.apache.org/contribute/release-guide/#create-a-new-version-in-jira

In any event, we should also archive the changes(.md or .txt) somewhere and understand if we in the future need to to this to JIRA

**Comment by houshengbo** [comment]
@mrutkows Since the very first release contains the initial code, we do not need it by far. This function will definitely be added for the further releases.

**Comment by dgrove-oss** [comment]
We are doing ok without scripting support for this.
