### ISSUE TITLE
OpenWhisk Release 19.09

### ISSUE THREAD

**Issue by dgrove-oss** [apache/openwhisk-release#241]
Top-level epic to coordinate the 19.08 Release of OpenWhisk

Runtimes
- [x] ~incubator-openwhisk-runtime-ballerina~ (wait for ballerina 1.0)
- [x] incubator-openwhisk-runtime-docker
- [x] incubator-openwhisk-runtime-dotnet
- [x] incubator-openwhisk-runtime-go
- [x] incubator-openwhisk-runtime-java
- [x] incubator-openwhisk-runtime-nodejs
- [x] incubator-openwhisk-runtime-php
- [x] incubator-openwhisk-runtime-python
- [x] incubator-openwhisk-runtime-ruby
- [x] incubator-openwhisk-runtime-swift

CLI
- [x] incubator-openwhisk-client-go
- [x] incubator-openwhisk-cli
- [x] incubator-openwhisk-wskdeploy

Catalog + Composer + Event Providers
- [x] incubator-openwhisk-apigateway
- [x] incubator-openwhisk-catalog
- [x] incubator-openwhisk-composer
- [x] ~incubator-openwhisk-composer-python~ (per @dgrove-oss needs more work)
- [x] incubator-openwhisk-package-alarms
- [x] incubator-openwhisk-package-cloudant
- [x] incubator-openwhisk-package-kafka

Core System
- [ ] incubator-openwhisk

Deployment projects
- [ ] incubator-openwhisk-deploy-kube

**Comment by jthomas** [comment]
Need to know include...
https://github.com/apache/incubator-openwhisk-pluggable-provider

**Comment by rabbah** [comment]
@jthomas i think we dont need the provider to the uber release in that there's no dependence from the core repo? 

i dropped ballerina until it has reached 1.0.

**Comment by dgrove-oss** [comment]
We're getting close to being able to do this. 
I think https://github.com/apache/openwhisk/issues/4829 should probably be a blocking issue though.  We shouldn't make a new release that exposes users to NodeJS 6, which is long past EOL.

**Comment by dgrove-oss** [comment]
Well; quite a long time later we finally got OpenWhisk 20.11 released.  Closing at last...
