### ISSUE TITLE
document signing releases with "own" pgp key

### ISSUE THREAD

**Issue by rabbah** [apache/openwhisk-release#265]
This is a reference 
https://github.com/apache/incubator-openwhisk-release/compare/master...rabbah:runtimes

- Fork the release repo
- travis encrypt SVN_USERNAME=yourname
- travis encrypt SVN_PASSWORD=password
- travis encrypt file your-pgp-secret-key
- update .travis file with corresponding values
- Push to your own fork with desired config.json 
- Travis does the rest

**Comment by dgrove-oss** [comment]
Meta-question.  Do you think we should use Travis for this automation and continually overwriting tools/config.json or should we be automating local builds with a workflow of doing a PR to add a new config.json for every release to the master branch of the main repo and then running a local command to build artifacts from that config.json (which would be kept in git, so it would document the input data for each released artifact).

**Comment by rabbah** [comment]
>  workflow of doing a PR to add a new config.json for every release to the master branch of the main repo and then running a local command to build artifacts from that config.json

This would be nice. I don't see why we can't commit the config.json with a unique name, matching the release name to git. The build script should accept a configuration file as a parameter instead of hardcoding config.json. The email generator script already requires specifying a config file.

**Comment by rabbah** [comment]
Instead of Travis, the semi-automatic build should be moved to our Apache Infra jenkins instead. The updated the documentation should disable the automatic Travis builds since they don't permit proper signing and a release manager must use the manual steps.

**Comment by dgrove-oss** [comment]
I will handle as part of improving documentation for release managers for doing local releases.
