### ISSUE TITLE
improvements to rcverify

### ISSUE THREAD

**Issue by dgrove-oss** [apache/openwhisk-release#272]
Feedback from an incubator voting thread (https://lists.apache.org/thread.html/9e320277655d931909fd85fe43c49bc4de1696d4e37939126fde7498@%3Cgeneral.incubator.apache.org%3E)

> One issue I see with the instructions script is that you are asking people to download it from head, this may make it hard to verify old releases or may give different results during the voting process if changes are made. It may be better to package the verifying script inside the release candidate.
> 
> Another is from the output of the script it’s unclear where it downloaded the files or what rc it is testing, adding that may be useful. It also clones incubator-openwhisk-utilities which might be seen as misleading as should it be cloning incubator-openwhisk-composer so it can compare what’s in version control to what in the release candidate. Again this seem to be checking out head which would change over time so it might be possible for it to give inconstant results.
>

**Comment by rabbah** [comment]
Thanks for pulling the feedback into an issue. 

I don't particularly like the idea of bundling rcverify with the release itself. What if we tagged version of rcverify instead? At face value, the latter is less work and I don't expect rcverify to change in ways that are backward breaking but I could be short sighted.

Similarly for scancode, we could tag versions - or create releases of this repo and only download the release to avoid the aforementioned confusion.

+1 to showing the download URL.

**Comment by dgrove-oss** [comment]
I agree that we don't want to bundle rcverify with each release.   

We could copy it into svn alongside the release candidate artifacts though, which would make it self-contained during the voting process.  Not sure if that is better than tagging, but maybe it is simpler.

**Comment by dgrove-oss** [comment]
I think we've dealt with this by having rcverify output the hash/tag as part of its output
