### ISSUE TITLE
Flatten subdirs or create 1.13 archive in Apache distribution archive 

### ISSUE THREAD

**Issue by mrutkows** [apache/openwhisk-release#277]
IMO, we should preserve the precedent to create subdirectories for versioned groups of component source code releases which will always contain the release artifacts for the corresponding release.

That is, within
[http://archive.apache.org/dist/incubator/openwhisk/](http://archive.apache.org/dist/incubator/openwhisk/)

we have archive folders for each of the major releases, but are only lacking the 1.13 subdirectory.

**Comment by dgrove-oss** [comment]
Please see prior discussion on dev list. The point is that there is not a useful semantics to grouping individual components by version numbers.

https://lists.apache.org/thread.html/8972e387e3e13ca97fee1c90cafae68b129753d303baaea4a0f805aa@%3Cdev.openwhisk.apache.org%3E

**Comment by mrutkows** [comment]
@dgrove-oss just want consistency that is backed by process documentation...  trying to figure out where the 1.13.0 release steps "broke down" (as they were not copied to the dist. archive site) and seeing that we had archive subdirs. for all but the most recent 0.11.0 and 1.13.0 it seemed steps were missed or automation lacked.   Flattened is fine, just document it and and see if we wish to make sure there are no confusing, legacy subdirs.

**Comment by mrutkows** [comment]
@rabbah @houshengbo @dgrove-oss we can repurpose this issue to "flatten" as there are no dissenters from the thread (with Carlos and Dom +1 to Dave).

**Comment by houshengbo** [comment]
@dgrove-oss @dgrove-oss @mrutkows 
Sorry, I missed this mail thread earlier. I got confused about why we flatten out the release. What is the the benefit??? What is wrong with a subdir with version name on it, hosting all the artifacts belong to that version? The release repo makes the structure the same way for our dev and release repo. I still insist on the current structure with version name folders.

**Comment by houshengbo** [comment]
Many other projects are still saving archives in hierarchical way based on version number, like in
http://archive.apache.org/dist/spark/
http://archive.apache.org/dist/brooklyn/
Why do we bother saving them in a flat manner?

**Comment by dgrove-oss** [comment]
We will create a subdirectory for each `unified` release that contains a set of releases that will actually work together.  The point is that the version number of each of our components is not aligned, so grouping by those numbers is not useful.
