### ISSUE TITLE
How can we generate the changlog and release note for each release

### ISSUE THREAD

**Issue by houshengbo** [apache/openwhisk-release#47]
We probably need to investigate the potential ways for this issue.

**Comment by houshengbo** [comment]
We have already got a script to generate the release note: https://github.com/apache/incubator-openwhisk-release/blob/master/docs/generate_release_notes.md

**Comment by dgrove-oss** [comment]
Closing as won't fix.  We've been doing reasonable well by doing this via manual inspection from the git log as we make releases.
