### ISSUE TITLE
tag repos with version after first release with openwhisk@0.1.0-incubating

### ISSUE THREAD

**Issue by csantanapr** [apache/openwhisk-release#61]
After the release is declared, the artifacts moved to the release svn folder, then all the repos included in the release at the respective git hash should be tag with a single label that is easy to distinguish the marker in the individual repos.

I propose to use tte convention `openwhisk@<version>` 

For the first release this will be in practice `openwhisk@0.1.0-incubating` and son on  `openwhisk@0.1.1-incubating`, `openwhisk@0.2.0-incubating`, `openwhisk@0.2.1-incubating`etc..

We can close this issue after first release and repos tagged.

cc @houshengbo

**Comment by houshengbo** [comment]
@csantanapr 
Based on what have now in config.json, we are able to define a major and a minor name for a release. For example, if the major name is "1.0" and the minor name is "GA", then the full name goes to "1.0-GA", which is included in the name of every artifact. I am not sure if this approach suffice our need.

**Comment by csantanapr** [comment]
@houshengbo 

The <release-version> can be compose using semver 2.0 MAJOR.MINOR.PATCH-PRERELEASE
Meaning during incubation we must have `-incubating` in the version.
For example:

During incubation:
- 0.1.0-incubating
- 0.2.0-incubating

After graduation (remove `-incubating`):
- 1.0.0
- 1.1.0
- 1.2.0

**Comment by houshengbo** [comment]
We are now ready to release openwhisk, once we pick up the hash values of all the openwhisk projects. We currently support the semantic 2.0, in order to configure the "MAJOR.MINOR.PATCH" and the "PRERELEASE" with the file config.json: https://github.com/apache/incubator-openwhisk-release/blob/master/docs/pick_up_source_code.md#edit-the-configuration-file.

**Comment by dgrove-oss** [comment]
this is being done by release managers and is documented.
